on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.TEST_WEBHOOK }}
        SLACK_ICON: https://github.com/Castellanos-Daniel/github-actions-tutorial/blob/slack-test/.github/workflows/assets/github_actions.png